# Generated by Django 2.1.5 on 2019-03-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('supplier', models.CharField(choices=[('KOR', 'Korea'), ('SGP', 'Singapore'), ('TWN', 'Taiwan')], max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('procurement_date', models.DateField(auto_now=True)),
                ('procurement_method', models.CharField(choices=[('PO', 'Pre Order'), ('SO', 'Self Order'), ('LA', 'Local Acquisition')], max_length=2)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
