# Generated by Django 2.1.5 on 2019-02-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inventory_get_date',
            new_name='item_get_date',
        ),
    ]
